### PR TITLE
Build Properties

### PR DESCRIPTION
**Pull request by nex-54**
TeamCity api provides Properties for build(/app/rest/builds/id:{id}).
Need to add Properties to Build class.

Issue #69 

### Checklist
- [x] All unit tests passed on build server
- [x] Acceptance test(s) covers new/modified functionality 
- [ ] Code coverage is at least the same or higher
- [x] Breaking change in public API

var myProperty = new RemoteTc().Connect(_ => _.ToHost("tc"))
                .GetBuild(123456).Properties.Property.Where(p => p.Name == "MyProperty");

### CODE REVIEW

**Comment by borismod** [comment]
@nex-54 thank you for your contribution. Have you committed unit tests and acceptance tests? Please make sure build passes after your changes: http://teamcity.codebetter.com/viewType.html?buildTypeId=FluentTc_FluentTcDevelop&branch_FluentTc=70%2Fmerge&tab=buildTypeStatusDiv

**Comment by nex-54** [comment]
@borismod i will check it.

**Comment by nex-54** [comment]
@borismod all tests are green. The only problem is smaller statement coverage. I'm not sure it is good idea to commit test for property add. But i can add test for BuildModelToBuildConverter to check if this property is ok after call ConvertToBuild.
I'm new on github, so should i do that or something else?

**Comment by nex-54** [comment]
@borismod how can i check unit tests on build server before make pull request?

**Comment by borismod** [comment]
Build server runs only from branches and pull requests. Can you run the
tests locally?

I am afraid that in order to improve code coverage, you'll have to add some
tests.

**Comment by nex-54** [comment]
Done.
Just figured out i take branch from master. Should i take branch from dev next time?

**Comment by borismod** [comment]
@nex-54 thanks! I'll take a look later to approve it. Branching from master is the preferred option. Usually  develop is even with master.

**Comment by borismod** [comment]
@nex-54 I appreciate your contribution and will merge this PR as well. It seems that this branch has conflicts. Can you please resolve them, so I could merge it?

**Comment by borismod** [comment]
@nex-54 what's your full name, so I could give you a credit on contributors list?

**Comment by nex-54** [comment]
@borismod conflicts are resolved
my full name is Artem Kuznetsov

**Pull request merged**
