### PR TITLE
Add support for running with both parameters and more options, fixes #83

### LINKED ISSUE #83: Start build with parameters and options
### Bug/Feature Request
I would like to start a build with custom parameters at the top of the build queue. I can do either or these, not both.

Happy to create a PR if you think this is valuable

### Test to reproduce
```C#
_Please provide necessary steps for reproduction of this issue_.
[Test]
public void Test_To_Reproduce_The_Issue()
{
   client.RunBuildConfiguration(_ => _.Id(someBuildConfig.Id),
                    _ => _.Parameter("testParam1", testParam1Value).Parameter("testParam2", testParam2Value), _ => _.QueueAtTop());
}
```

### Affected versions

Product | Version
--------|--------
FluentTc |  latest
TeamCity | any
Autofac |
EasyHttp |
SharpZipLib |
System.IO.Abstractions | 
TeamCity.ServiceMessages |

### PR DESCRIPTION
**Pull request by evolvedlight**
Hi

This fixes #83 - sorry, missed the github keyword to associate these properly.

### CODE REVIEW

**Comment by borismod** [comment]
@evolvedlight thanks for your contribution. Can you please make sure the build passes? 
https://teamcity.jetbrains.com/viewLog.html?buildId=915857&buildTypeId=FluentTc_FluentTcDevelop

**Comment by evolvedlight** [comment]
Hi @borismod 
It looks like it already does for my merge build, just not the develop branch?
https://teamcity.jetbrains.com/viewLog.html?buildId=915861&buildTypeId=FluentTc_FluentTcDevelop&tab=buildChangesDiv

**Comment by borismod** [comment]
No, it runs on the PR and it's not merged yet.
https://teamcity.jetbrains.com/viewType.html?buildTypeId=FluentTc_FluentTcDevelop

**Comment by borismod** [comment]
The compilation of your code succeeded and all the tests passed as well. It's just the coverage is a little bit lower than it was. Can you please make it at least as it was or higher?

Thanks

**Comment by evolvedlight** [comment]
Hi

Sorry, you might have to give me more of a hint where to look. The current master is https://teamcity.jetbrains.com/viewLog.html?buildId=906978&tab=buildResultsDiv&buildTypeId=FluentTc and my changes are https://teamcity.jetbrains.com/viewLog.html?buildId=915861&tab=buildResultsDiv&buildTypeId=FluentTc_FluentTcDevelop. My changes have a slightly higher coverage % than master. The build you are linking to is related to a branch not from me, as far as I can tell (https://teamcity.jetbrains.com/viewLog.html?buildId=915857&buildTypeId=FluentTc_FluentTcDevelop&tab=buildChangesDiv shows the change not from me). I can add more tests, if you want, however I suspect it's not going to increase coverage significantly as the new code I've added looks like it's fully covered.

**Comment by borismod** [comment]
@evolvedlight my fault, you're right. Anyway I am going to migrate the CI to AppVeyor and to make the process of PR more friction-less that it's now. 
Thanks for your contribution!

**Comment by borismod** [comment]
Nuget published 0.0.0.210
https://www.nuget.org/packages/fluenttc

**Comment by evolvedlight** [comment]
Great, thanks!

**Pull request merged**
